name: ITS Checker

on:
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npx playwright install --with-deps

      - run: node check.js
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: |
            page.html
            page.png
